### ISSUE TITLE
Setting path curvature doesn't update shadows

### ISSUE THREAD

**Issue by maxpaulus43** [ArmindoFlores/obr-fogofwar#3]
![image](https://user-images.githubusercontent.com/4512696/234693855-d0b0d1aa-955e-4dec-84c6-1cde68dcf586.png)

Setting that button curves the path, but the shadows don't update.

**Comment by ArmindoFlores** [comment]
The shadows are based only on the points that are part of the lines and I don't plan on supporting curves at the moment.
